services:
  - type: web
    name: firelevel-api
    env: go
    buildCommand: go build -o server ./cmd/api
    startCommand: ./server
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: DB_CONNECTION_STRING
        sync: false
